#server port number
server:
  port: 8080

#spring related configurations
spring:
  application:
    name: "accounts"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:h2:mem:prabindb
    driverClassName: org.h2.Driver
    username: root
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

# actuator related configurations
management:
  endpoints:
    web:
      exposure:
        include: "*"

